name: Release CV

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    env:
      TEX_FILE: "Artem Basalaev CV.tex"
      PDF_FILE: "Artem Basalaev CV.pdf"

    steps:
    - name: Set up Git repository
      id: setup-git-repository
      uses: actions/checkout@v4
    - name: Compile LaTeX document
      id: compile-latex-document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: "*.tex"
    - name: Upload Artifact for GitHub Pages
      id: upload-artifact-for-github-pages
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: |
          *.pdf
          pages/*
    - name: Retrieve date
      id: resolve-date
      run: |
        DATE="$(date +'%Y-%m-%d')"
        echo "date=$DATE" >> "$GITHUB_OUTPUT"
    - name: Create or update release
      id: create-or-update-release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.resolve_date.outputs.date }}
        allowUpdates: true
        artifacts: "*.pdf"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        artifact_name: "github-pages"
