name: Release CV

on:
  push:
    branches:
    - master

jobs:
  build_latex:
    runs-on: ubuntu-latest
    env:
      TEX_FILE: "Artem Basalaev CV.tex"
      PDF_FILE: "Artem Basalaev CV.pdf"
    steps:
    - name: Set up Git repository
      id: setup_git_repository
      uses: actions/checkout@v4
    - name: Compile LaTeX document
      id: compile_latex_document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: "*.pdf"
    - name: Upload PDF file
      id: upload_pdf_file
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: "*.pdf"
    - name: Retrieve date
      id: resolve_date
      run: |
        DATE="$(date +'%d.%m.%Y')"
        echo "date=$DATE" >> "$GITHUB_OUTPUT"
    - name: Create or update release
      id: create_or_update_release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.resolve_date.outputs.date }}
        allowUpdates: true
        artifacts: "*.pdf"
